
Public Class MainMenu

    Sub switchPanel(ByVal panel As Form)
        MainPanel.Controls.Clear()
        panel.TopLevel = False
        MainPanel.Controls.Add(panel)
        panel.Show()
    End Sub
    Private Sub MainBTN_Click(sender As Object, e As EventArgs) Handles MainBTN.Click
        switchPanel(NowShowingForm)
        HighlightMain.Visible = True
        HighlightGenre.Visible = False
        HighlightBeverages.Visible = False
        HighlightScreen.Visible = False
    End Sub

    Private Sub GenreBTN_Click(sender As Object, e As EventArgs) Handles GenreBTN.Click
        switchPanel(GenreForm)
        HighlightMain.Visible = False
        HighlightGenre.Visible = True
        HighlightBeverages.Visible = False
        HighlightScreen.Visible = False
    End Sub

    Private Sub BeverageBTN_Click(sender As Object, e As EventArgs) Handles BeverageBTN.Click
        switchPanel(Beverages)
        HighlightMain.Visible = False
        HighlightGenre.Visible = False
        HighlightBeverages.Visible = True
        HighlightScreen.Visible = False
    End Sub

    Private Sub ScreenBTN_Click(sender As Object, e As EventArgs) Handles ScreenBTN.Click
        switchPanel(AboutUs)
        HighlightMain.Visible = False
        HighlightGenre.Visible = False
        HighlightBeverages.Visible = False
        HighlightScreen.Visible = True
    End Sub
    Private Sub SlideButton1_Click(sender As Object, e As EventArgs) Handles SlideButton1.Click
        If SlideButton1.IsOn = True Then

            Me.BackColor = Color.FromArgb(245, 237, 237)
            NowShowingForm.BackColor = Color.FromArgb(245, 237, 237)
            NowShowingForm.recommendedLabel.ForeColor = Color.Black
            NowShowingForm.RatingNM1.ForeColor = Color.Black
            NowShowingForm.RatingNM2.ForeColor = Color.Black
            NowShowingForm.RatingNM3.ForeColor = Color.Black
            NowShowingForm.RatingNM4.ForeColor = Color.Black
            NowShowingForm.Nname1.ForeColor = Color.Black
            NowShowingForm.Nname2.ForeColor = Color.Black
            NowShowingForm.Nname3.ForeColor = Color.Black
            NowShowingForm.Nname4.ForeColor = Color.Black

            GenreForm.BackColor = Color.FromArgb(245, 237, 237)
            GenreForm.HitLabel.ForeColor = Color.Black
            GenreForm.AboutHitLable.ForeColor = Color.Black
            GenreForm.HLabel.ForeColor = Color.Black
            GenreForm.CLabel.ForeColor = Color.Black
            GenreForm.ALabel.ForeColor = Color.Black
            GenreForm.RLabel.ForeColor = Color.Black
            GenreForm.Hname1.ForeColor = Color.Black
            GenreForm.Hname2.ForeColor = Color.Black
            GenreForm.Cname1.ForeColor = Color.Black
            GenreForm.Cname2.ForeColor = Color.Black
            GenreForm.Aname1.ForeColor = Color.Black
            GenreForm.Aname2.ForeColor = Color.Black
            GenreForm.Rname1.ForeColor = Color.Black
            GenreForm.Rname2.ForeColor = Color.Black
            GenreForm.RatingH1.ForeColor = Color.Black
            GenreForm.RatingH2.ForeColor = Color.Black
            GenreForm.RatingC1.ForeColor = Color.Black
            GenreForm.RatingC2.ForeColor = Color.Black
            GenreForm.RatingA1.ForeColor = Color.Black
            GenreForm.RatingA2.ForeColor = Color.Black
            GenreForm.RatingR1.ForeColor = Color.Black
            GenreForm.RatingR2.ForeColor = Color.Black

            Beverages.BackColor = Color.FromArgb(245, 237, 237)
            Beverages.nachostxt1.ForeColor = Color.Black
            Beverages.nachostxt2.ForeColor = Color.Black
            Beverages.nachostxt3.ForeColor = Color.Black
            Beverages.coketxt1.ForeColor = Color.Black
            Beverages.coketxt2.ForeColor = Color.Black
            Beverages.coketxt3.ForeColor = Color.Black
            Beverages.popcorntxt1.ForeColor = Color.Black
            Beverages.popcorntxt2.ForeColor = Color.Black
            Beverages.popcorntxt3.ForeColor = Color.Black
            Beverages.popcorncarameltxt1.ForeColor = Color.Black
            Beverages.popcorncarameltxt2.ForeColor = Color.Black
            Beverages.popcorncarameltxt3.ForeColor = Color.Black
            Beverages.popcorncheesetxt1.ForeColor = Color.Black
            Beverages.popcorncheesetxt2.ForeColor = Color.Black
            Beverages.popcorncheesetxt1.ForeColor = Color.Black
            Beverages.combotxt1.ForeColor = Color.Black
            Beverages.combotxt2.ForeColor = Color.Black
            Beverages.combotxt3.ForeColor = Color.Black

            Beverages2.BackColor = Color.FromArgb(245, 237, 237)
            Beverages2.nachostxt1.ForeColor = Color.Black
            Beverages2.nachostxt2.ForeColor = Color.Black
            Beverages2.nachostxt3.ForeColor = Color.Black
            Beverages2.coketxt1.ForeColor = Color.Black
            Beverages2.coketxt2.ForeColor = Color.Black
            Beverages2.coketxt3.ForeColor = Color.Black
            Beverages2.popcorntxt1.ForeColor = Color.Black
            Beverages2.popcorntxt2.ForeColor = Color.Black
            Beverages2.popcorntxt3.ForeColor = Color.Black
            Beverages2.popcorncarameltxt1.ForeColor = Color.Black
            Beverages2.popcorncarameltxt2.ForeColor = Color.Black
            Beverages2.popcorncarameltxt3.ForeColor = Color.Black
            Beverages2.popcorncheesetxt1.ForeColor = Color.Black
            Beverages2.popcorncheesetxt2.ForeColor = Color.Black
            Beverages2.popcorncheesetxt1.ForeColor = Color.Black
            Beverages2.combotxt1.ForeColor = Color.Black
            Beverages2.combotxt2.ForeColor = Color.Black
            Beverages2.combotxt3.ForeColor = Color.Black

            AboutUs.BackColor = Color.FromArgb(245, 237, 237)
            AboutUs.abt_pnl.BackColor = Color.FromArgb(245, 237, 237)
            AboutUs.abt_us_lbl.ForeColor = Color.Black
            AboutUs.abt_us_detail_lbl.ForeColor = Color.Black

            The_Nun.BackColor = Color.FromArgb(245, 237, 237)
            The_Nun.nun_panel.BackColor = Color.FromArgb(245, 237, 237)
            The_Nun.nun_format_pnl.BackColor = Color.FromArgb(245, 237, 237)
            The_Nun.Rating_lbl.ForeColor = Color.Black
            The_Nun.dur_lbl.ForeColor = Color.Black
            The_Nun.dur_time_lbl.ForeColor = Color.Black
            The_Nun.rating_val_lbl.ForeColor = Color.Black
            The_Nun.nun_desc.ForeColor = Color.Black
            The_Nun.cast_lbl.ForeColor = Color.Black
            The_Nun.cname1.ForeColor = Color.Black
            The_Nun.cname2.ForeColor = Color.Black
            The_Nun.cname3.ForeColor = Color.Black
            The_Nun.cname4.ForeColor = Color.Black
            The_Nun.top_review_lbl.ForeColor = Color.Black
            The_Nun.reviews_lbl.ForeColor = Color.Black
            The_Nun.user1_lbl.ForeColor = Color.Black
            The_Nun.user1_review_lbl.ForeColor = Color.Black
            The_Nun.user2_name_lbl.ForeColor = Color.Black
            The_Nun.user2_review_lbl.ForeColor = Color.Black
            The_Nun.username_lbl.ForeColor = Color.Black
            The_Nun.user_review_output.ForeColor = Color.Black
            The_Nun.add_review_lbl.ForeColor = Color.Black
            The_Nun.user_review_txt.ForeColor = Color.Black
            The_Nun.moviename_lbl.ForeColor = Color.Black
            The_Nun.format_nxt_btn.ForeColor = Color.Black
            The_Nun.next_btn.ForeColor = Color.Black
            The_Nun.select_format_lbl.ForeColor = Color.Black
            The_Nun.btn_2d.ForeColor = Color.Black
            The_Nun.btn_3d.ForeColor = Color.Black
            The_Nun.Add_btn.ForeColor = Color.Black

            saw.sw_format_pnl.BackColor = Color.FromArgb(245, 237, 237)
            saw.BackColor = Color.FromArgb(245, 237, 237)
            saw.saw_panel.BackColor = Color.FromArgb(245, 237, 237)
            saw.sw_Rating_lbl.ForeColor = Color.Black
            saw.sw_dur_lbl.ForeColor = Color.Black
            saw.sw_dur_time_lbl.ForeColor = Color.Black
            saw.sw_rating_val_lbl.ForeColor = Color.Black
            saw.sw_desc.ForeColor = Color.Black
            saw.sw_cast_lbl.ForeColor = Color.Black
            saw.sw_cname1.ForeColor = Color.Black
            saw.sw_cname2.ForeColor = Color.Black
            saw.sw_cname3.ForeColor = Color.Black
            saw.sw_cname4.ForeColor = Color.Black
            saw.sw_top_review_lbl.ForeColor = Color.Black
            saw.reviews_lbl.ForeColor = Color.Black
            saw.sw_user1_lbl.ForeColor = Color.Black
            saw.sw_user1_review_lbl.ForeColor = Color.Black
            saw.sw_user2_name_lbl.ForeColor = Color.Black
            saw.sw_user2_review_lbl.ForeColor = Color.Black
            saw.sw_username_lbl.ForeColor = Color.Black
            saw.sw_user_review_output.ForeColor = Color.Black
            saw.sw_add_review_lbl.ForeColor = Color.White
            saw.sw_user_review_txt.ForeColor = Color.Black
            saw.sw_moviename_lbl.ForeColor = Color.Black
            saw.sw_format_nxt_btn.ForeColor = Color.Black
            saw.sw_next_btn.ForeColor = Color.Black
            saw.sw_select_format_lbl.ForeColor = Color.Black
            saw.sw_btn_2d.ForeColor = Color.Black
            saw.sw_btn_3d.ForeColor = Color.Black
            saw.sw_Add_btn.ForeColor = Color.Black

            'SUZUME DARK MODE CODE
            suzume.suz_format_pnl.BackColor = Color.FromArgb(245, 237, 237)
            suzume.BackColor = Color.FromArgb(245, 237, 237)
            suzume.suz_panel.BackColor = Color.FromArgb(245, 237, 237)
            suzume.s_Rating_lbl.ForeColor = Color.Black
            suzume.s_dur_lbl.ForeColor = Color.Black
            suzume.s_dur_time_lbl.ForeColor = Color.Black
            suzume.s_rating_val_lbl.ForeColor = Color.Black
            suzume.s_desc.ForeColor = Color.Black
            suzume.s_cast_lbl.ForeColor = Color.Black
            suzume.s_cname1.ForeColor = Color.Black
            suzume.s_cname2.ForeColor = Color.Black
            suzume.s_cname3.ForeColor = Color.Black
            suzume.s_cname4.ForeColor = Color.Black
            suzume.s_top_review_lbl.ForeColor = Color.Black
            suzume.s_reviews_lbl.ForeColor = Color.Black
            suzume.s_user1_lbl.ForeColor = Color.Black
            suzume.s_user1_review_lbl.ForeColor = Color.Black
            suzume.s_user2_name_lbl.ForeColor = Color.Black
            suzume.s_user2_review_lbl.ForeColor = Color.Black
            suzume.s_username_lbl.ForeColor = Color.Black
            suzume.s_user_review_output.ForeColor = Color.Black
            suzume.s_add_review_lbl.ForeColor = Color.White
            suzume.s_user_review_txt.ForeColor = Color.Black
            suzume.s_moviename_lbl.ForeColor = Color.Black
            suzume.s_format_nxt_btn.ForeColor = Color.Black
            suzume.s_next_btn.ForeColor = Color.Black
            suzume.s_select_format_lbl.ForeColor = Color.Black
            suzume.s_btn_2d.ForeColor = Color.Black
            suzume.s_btn_3d.ForeColor = Color.Black
            suzume.s_Add_btn.ForeColor = Color.Black
            'PATHAN DARK MODE CODE
            pathan.BackColor = Color.FromArgb(245, 237, 237)
            pathan.pathan_panel.BackColor = Color.FromArgb(245, 237, 237)
            pathan.pathan_format_pnl.BackColor = Color.FromArgb(245, 237, 237)
            pathan.pt_Rating_lbl.ForeColor = Color.Black
            pathan.pt_dur_lbl.ForeColor = Color.Black
            pathan.pt_dur_time_lbl.ForeColor = Color.Black
            pathan.pt_rating_val_lbl.ForeColor = Color.Black
            pathan.pt_desc.ForeColor = Color.Black
            pathan.pt_cast_lbl.ForeColor = Color.Black
            pathan.pt_cname1.ForeColor = Color.Black
            pathan.pt_cname2.ForeColor = Color.Black
            pathan.pt_cname3.ForeColor = Color.Black
            pathan.pt_cname4.ForeColor = Color.Black
            pathan.pt_top_review_lbl.ForeColor = Color.Black
            pathan.pt_reviews_lbl.ForeColor = Color.Black
            pathan.pt_user1_lbl.ForeColor = Color.Black
            pathan.pt_user1_review_lbl.ForeColor = Color.Black
            pathan.pt_user2_name_lbl.ForeColor = Color.Black
            pathan.pt_user2_review_lbl.ForeColor = Color.Black
            pathan.pt_username_lbl.ForeColor = Color.Black
            pathan.pt_user_review_output.ForeColor = Color.Black
            pathan.pt_add_review_lbl.ForeColor = Color.White
            pathan.pt_user_review_txt.ForeColor = Color.Black
            pathan.pt_moviename_lbl.ForeColor = Color.Black
            pathan.pt_format_nxt_btn.ForeColor = Color.Black
            pathan.pt_next_btn.ForeColor = Color.Black
            pathan.pt_select_format_lbl.ForeColor = Color.Black
            pathan.pt_btn_2d.ForeColor = Color.Black
            pathan.pt_btn_3d.ForeColor = Color.Black
            pathan.pt_Add_btn.ForeColor = Color.Black
            'RADHE DARK MODE CODE
            Radhe.BackColor = Color.FromArgb(245, 237, 237)
            Radhe.radhe_panel.BackColor = Color.FromArgb(245, 237, 237)
            Radhe.radhe_format_pnl.BackColor = Color.FromArgb(245, 237, 237)
            Radhe.rd_Rating_lbl.ForeColor = Color.Black
            Radhe.rd_dur_lbl.ForeColor = Color.Black
            Radhe.rd_dur_time_lbl.ForeColor = Color.Black
            Radhe.rd_rating_val_lbl.ForeColor = Color.Black
            Radhe.rd_desc.ForeColor = Color.Black
            Radhe.rd_cast_lbl.ForeColor = Color.Black
            Radhe.rd_cname1.ForeColor = Color.Black
            Radhe.rd_cname2.ForeColor = Color.Black
            Radhe.rd_cname3.ForeColor = Color.Black
            Radhe.rd_cname4.ForeColor = Color.Black
            Radhe.rd_top_review_lbl.ForeColor = Color.Black
            Radhe.rd_reviews_lbl.ForeColor = Color.Black
            Radhe.rd_user1_lbl.ForeColor = Color.Black
            Radhe.rd_user1_review_lbl.ForeColor = Color.Black
            Radhe.rd_user2_name_lbl.ForeColor = Color.Black
            Radhe.rd_user2_review_lbl.ForeColor = Color.Black
            Radhe.rd_username_lbl.ForeColor = Color.Black
            Radhe.rd_user_review_output.ForeColor = Color.Black
            Radhe.rd_add_review_lbl.ForeColor = Color.White
            Radhe.rd_user_review_txt.ForeColor = Color.Black
            Radhe.rd_moviename_lbl.ForeColor = Color.Black
            Radhe.rd_format_nxt_btn.ForeColor = Color.Black
            Radhe.rd_next_btn.ForeColor = Color.Black
            Radhe.rd_select_format_lbl.ForeColor = Color.Black
            Radhe.rd_btn_2d.ForeColor = Color.Black
            Radhe.rd_btn_3d.ForeColor = Color.Black
            Radhe.rd_Add_btn.ForeColor = Color.Black
            'TITANIC DARK MODE CODE
            Titanic.BackColor = Color.FromArgb(245, 237, 237)
            Titanic.Titanic_panel.BackColor = Color.FromArgb(245, 237, 237)
            Titanic.titanic_format_pnl.BackColor = Color.FromArgb(245, 237, 237)
            Titanic.TT_Rating_lbl.ForeColor = Color.Black
            Titanic.TT_dur_lbl.ForeColor = Color.Black
            Titanic.TT_dur_time_lbl.ForeColor = Color.Black
            Titanic.TT_rating_val_lbl.ForeColor = Color.Black
            Titanic.titanic_desc.ForeColor = Color.Black
            Titanic.tt_cast_lbl.ForeColor = Color.Black
            Titanic.TT_cname1.ForeColor = Color.Black
            Titanic.TT_cname2.ForeColor = Color.Black
            Titanic.TT_cname3.ForeColor = Color.Black
            Titanic.TT_cname4.ForeColor = Color.Black
            Titanic.TT_top_review_lbl.ForeColor = Color.Black
            Titanic.TT_reviews_lbl.ForeColor = Color.Black
            Titanic.TT_user1_lbl.ForeColor = Color.Black
            Titanic.TT_user1_review_lbl.ForeColor = Color.Black
            Titanic.TT_user2_name_lbl.ForeColor = Color.Black
            Titanic.TT_user2_review_lbl.ForeColor = Color.Black
            Titanic.TT_username_lbl.ForeColor = Color.Black
            Titanic.TT_user_review_output.ForeColor = Color.Black
            Titanic.TT_add_review_lbl.ForeColor = Color.White
            Titanic.TT_user_review_txt.ForeColor = Color.Black
            Titanic.TT_moviename_lbl.ForeColor = Color.Black
            Titanic.TT_format_nxt_btn.ForeColor = Color.Black
            Titanic.TT_next_btn.ForeColor = Color.Black
            Titanic.TT_select_format_lbl.ForeColor = Color.Black
            Titanic.TT_btn_2d.ForeColor = Color.Black
            Titanic.TT_btn_3d.ForeColor = Color.Black
            Titanic.TT_Add_btn.ForeColor = Color.Black
            'POSTER BOYS DARK MODE CODE
            poster_boys.BackColor = Color.FromArgb(245, 237, 237)
            poster_boys.poster_panel.BackColor = Color.FromArgb(245, 237, 237)
            poster_boys.poster_format_pnl.BackColor = Color.FromArgb(245, 237, 237)
            poster_boys.pb_Rating_lbl.ForeColor = Color.Black
            poster_boys.pb_dur_lbl.ForeColor = Color.Black
            poster_boys.pb_dur_time_lbl.ForeColor = Color.Black
            poster_boys.pb_rating_val_lbl.ForeColor = Color.Black
            poster_boys.pb_desc.ForeColor = Color.Black
            poster_boys.pb_cast_lbl.ForeColor = Color.Black
            poster_boys.pb_cname1.ForeColor = Color.Black
            poster_boys.pb_cname2.ForeColor = Color.Black
            poster_boys.pb_cname3.ForeColor = Color.Black
            poster_boys.pb_cname4.ForeColor = Color.Black
            poster_boys.pb_top_review_lbl.ForeColor = Color.Black
            poster_boys.pb_reviews_lbl.ForeColor = Color.Black
            poster_boys.pb_user1_lbl.ForeColor = Color.Black
            poster_boys.pb_user1_review_lbl.ForeColor = Color.Black
            poster_boys.pb_user2_name_lbl.ForeColor = Color.Black
            poster_boys.pb_user2_review_lbl.ForeColor = Color.Black
            poster_boys.pb_username_lbl.ForeColor = Color.Black
            poster_boys.pb_user_review_output.ForeColor = Color.Black
            poster_boys.pb_add_review_lbl.ForeColor = Color.White
            poster_boys.pb_user_review_txt.ForeColor = Color.Black
            poster_boys.pb_moviename_lbl.ForeColor = Color.Black
            poster_boys.pb_format_nxt_btn.ForeColor = Color.Black
            poster_boys.pb_next_btn.ForeColor = Color.Black
            poster_boys.pb_select_format_lbl.ForeColor = Color.Black
            poster_boys.pb_btn_2d.ForeColor = Color.Black
            poster_boys.pb_btn_3d.ForeColor = Color.Black
            poster_boys.pb_Add_btn.ForeColor = Color.Black
            'SHINCHAN DARK MODE CODE
            Shinchan.BackColor = Color.FromArgb(245, 237, 237)
            Shinchan.shinchan_panel.BackColor = Color.FromArgb(245, 237, 237)
            Shinchan.shinchan_format_pnl.BackColor = Color.FromArgb(245, 237, 237)
            Shinchan.sc_Rating_lbl.ForeColor = Color.Black
            Shinchan.sc_dur_lbl.ForeColor = Color.Black
            Shinchan.sc_dur_time_lbl.ForeColor = Color.Black
            Shinchan.sc_rating_val_lbl.ForeColor = Color.Black
            Shinchan.sc_desc.ForeColor = Color.Black
            Shinchan.sc_cast_lbl.ForeColor = Color.Black
            Shinchan.sc_cname1.ForeColor = Color.Black
            Shinchan.sc_cname2.ForeColor = Color.Black
            Shinchan.sc_cname3.ForeColor = Color.Black
            Shinchan.sc_cname4.ForeColor = Color.Black
            Shinchan.sc_top_review_lbl.ForeColor = Color.Black
            Shinchan.sc_reviews_lbl.ForeColor = Color.Black
            Shinchan.sc_user1_lbl.ForeColor = Color.Black
            Shinchan.sc_user1_review_lbl.ForeColor = Color.Black
            Shinchan.sc_user2_name_lbl.ForeColor = Color.Black
            Shinchan.sc_user2_review_lbl.ForeColor = Color.Black
            Shinchan.sc_username_lbl.ForeColor = Color.Black
            Shinchan.sc_user_review_output.ForeColor = Color.Black
            Shinchan.sc_add_review_lbl.ForeColor = Color.White
            Shinchan.sc_user_review_txt.ForeColor = Color.Black
            Shinchan.sc_moviename_lbl.ForeColor = Color.Black
            Shinchan.sc_format_nxt_btn.ForeColor = Color.Black
            Shinchan.sc_next_btn.ForeColor = Color.Black
            Shinchan.sc_select_format_lbl.ForeColor = Color.Black
            Shinchan.sc_btn_2d.ForeColor = Color.Black
            Shinchan.sc_btn_3d.ForeColor = Color.Black
            Shinchan.sc_Add_btn.ForeColor = Color.Black
            'Lallu DARKMODE CODE
            Lallu.BackColor = Color.FromArgb(245, 237, 237)
            Lallu.lallu_panel.BackColor = Color.FromArgb(245, 237, 237)
            Lallu.lallu_format_pnl.BackColor = Color.FromArgb(245, 237, 237)
            Lallu.ll_Rating_lbl.ForeColor = Color.Black
            Lallu.ll_dur_lbl.ForeColor = Color.Black
            Lallu.ll_dur_time_lbl.ForeColor = Color.Black
            Lallu.ll_rating_val_lbl.ForeColor = Color.Black
            Lallu.ll_desc.ForeColor = Color.Black
            Lallu.ll_cast_lbl.ForeColor = Color.Black
            Lallu.ll_cname1.ForeColor = Color.Black
            Lallu.ll_cname2.ForeColor = Color.Black
            Lallu.ll_cname3.ForeColor = Color.Black
            Lallu.ll_cname4.ForeColor = Color.Black
            Lallu.ll_top_review_lbl.ForeColor = Color.Black
            Lallu.ll_reviews_lbl.ForeColor = Color.Black
            Lallu.ll_user1_lbl.ForeColor = Color.Black
            Lallu.ll_user1_review_lbl.ForeColor = Color.Black
            Lallu.ll_user2_name_lbl.ForeColor = Color.Black
            Lallu.ll_user2_review_lbl.ForeColor = Color.Black
            Lallu.ll_username_lbl.ForeColor = Color.Black
            Lallu.ll_user_review_output.ForeColor = Color.Black
            Lallu.ll_add_review_lbl.ForeColor = Color.White
            Lallu.ll_user_review_txt.ForeColor = Color.Black
            Lallu.ll_moviename_lbl.ForeColor = Color.Black
            Lallu.ll_format_nxt_btn.ForeColor = Color.Black
            Lallu.ll_next_btn.ForeColor = Color.Black
            Lallu.II_select_format_lbl.ForeColor = Color.Black
            Lallu.ll_btn_2d.ForeColor = Color.Black
            Lallu.ll_btn_3d.ForeColor = Color.Black
            Lallu.ll_Add_btn.ForeColor = Color.Black

            TandC.BackColor = Color.FromArgb(245, 237, 237)
            TandC.Label2.ForeColor = Color.Black

            movie1___Date1__.todaypathandate1.BackColor = Color.FromArgb(245, 237, 237)
            movie1___Date1__.tomorrowpathandate1.BackColor = Color.FromArgb(245, 237, 237)
            movie1___Date1__.Dayaftertomorrowpathandate1.BackColor = Color.FromArgb(245, 237, 237)
            movie1___Date1__.todaypathandate1.ForeColor = Color.Black
            movie1___Date1__.tomorrowpathandate1.ForeColor = Color.Black
            movie1___Date1__.Dayaftertomorrowpathandate1.ForeColor = Color.Black

            movie1_date1_.panelPanel2today.BackColor = Color.FromArgb(245, 237, 237)
            movie1_date1_.screen1movie1date1.ForeColor = Color.Black
            movie1_date1_.screen1movie1date1.BackColor = Color.FromArgb(245, 237, 237)
            movie1_date1_.screen2movie1date1.ForeColor = Color.Black
            movie1_date1_.screen2movie1date1.BackColor = Color.FromArgb(245, 237, 237)
            movie1_date1_.screen3moviedate1.ForeColor = Color.Black
            movie1_date1_.screen3moviedate1.BackColor = Color.FromArgb(245, 237, 237)
            movie1_date1_.noncancellable1.ForeColor = Color.Black
            movie1_date1_.noncancellable2.ForeColor = Color.Black
            movie1_date1_.cancellable1.ForeColor = Color.Black

            movie1___Date_2__.Panel2tomorrow.BackColor = Color.FromArgb(245, 237, 237)
            movie1___Date_2__.screen1movie1date2.ForeColor = Color.Black
            movie1___Date_2__.screen2movie1date2.ForeColor = Color.Black
            movie1___Date_2__.screen3moviedate2.ForeColor = Color.Black
            movie1___Date_2__.noncancellable1date2.ForeColor = Color.Black
            movie1___Date_2__.noncancellable2date2.ForeColor = Color.Black
            movie1___Date_2__.cancellable1date2.ForeColor = Color.Black

            movie1___date_3_.panelPanel2dayaftertomorrow.BackColor = Color.FromArgb(245, 237, 237)
            movie1___date_3_.screen1movie1date3.ForeColor = Color.Black
            movie1___date_3_.screen2movie1date3.ForeColor = Color.Black
            movie1___date_3_.screen3moviedate3.ForeColor = Color.Black
            movie1___date_3_.noncancellable1date3.ForeColor = Color.Black
            movie1___date_3_.noncancellable2date3.ForeColor = Color.Black
            movie1___date_3_.cancellable1date3.ForeColor = Color.Black

            Screen1.BackColor = Color.FromArgb(245, 237, 237)
            Screen1.Label1.ForeColor = Color.Black
            Screen1.Label2.ForeColor = Color.Black
            Screen1.Label3.ForeColor = Color.Black
            Screen1.Label4.ForeColor = Color.Black
            Screen1.Label13.ForeColor = Color.Black
            Screen1.Label28.ForeColor = Color.Black
            Screen1.Label29.ForeColor = Color.Black

            Screen2.BackColor = Color.FromArgb(245, 237, 237)
            Screen2.Label1.ForeColor = Color.Black
            Screen2.Label2.ForeColor = Color.Black
            Screen2.Label3.ForeColor = Color.Black
            Screen2.Label4.ForeColor = Color.Black
            Screen2.Label13.ForeColor = Color.Black
            Screen2.Label28.ForeColor = Color.Black
            Screen2.Label29.ForeColor = Color.Black

            PaymentForm.Panel1.BackColor = Color.FromArgb(245, 237, 237)
            PaymentForm.Panel1.ForeColor = Color.Black

            TicketForm.BackColor = Color.FromArgb(245, 237, 237)
            TicketForm.ScanLabel.ForeColor = Color.Black
            TicketForm.ForeColor = Color.Black
            TicketForm.Label1.ForeColor = Color.Black
            TicketForm.Label2.ForeColor = Color.Black
            TicketForm.Label3.ForeColor = Color.Black
            TicketForm.Label4.ForeColor = Color.Black
            TicketForm.SeatLabel.ForeColor = Color.Black
            TicketForm.TotalLabel.ForeColor = Color.Black
            TicketForm.BevLabel.ForeColor = Color.Black
            TicketForm.TotLabel.ForeColor = Color.Black

        ElseIf SlideButton1.IsOn = False Then
            Me.BackColor = Color.FromArgb(0, 0, 0)
            NowShowingForm.BackColor = Color.FromArgb(0, 0, 0)
            NowShowingForm.recommendedLabel.ForeColor = Color.White
            NowShowingForm.RatingNM1.ForeColor = Color.White
            NowShowingForm.RatingNM2.ForeColor = Color.White
            NowShowingForm.RatingNM3.ForeColor = Color.White
            NowShowingForm.RatingNM4.ForeColor = Color.White
            NowShowingForm.Nname1.ForeColor = Color.White
            NowShowingForm.Nname2.ForeColor = Color.White
            NowShowingForm.Nname3.ForeColor = Color.White
            NowShowingForm.Nname4.ForeColor = Color.White

            GenreForm.BackColor = Color.FromArgb(0, 0, 0)
            GenreForm.HitLabel.ForeColor = Color.White
            GenreForm.AboutHitLable.ForeColor = Color.White
            GenreForm.HLabel.ForeColor = Color.White
            GenreForm.CLabel.ForeColor = Color.White
            GenreForm.ALabel.ForeColor = Color.White
            GenreForm.RLabel.ForeColor = Color.White
            GenreForm.Hname1.ForeColor = Color.White
            GenreForm.Hname2.ForeColor = Color.White
            GenreForm.Cname1.ForeColor = Color.White
            GenreForm.Cname2.ForeColor = Color.White
            GenreForm.Aname1.ForeColor = Color.White
            GenreForm.Aname2.ForeColor = Color.White
            GenreForm.Rname1.ForeColor = Color.White
            GenreForm.Rname2.ForeColor = Color.White
            GenreForm.RatingH1.ForeColor = Color.White
            GenreForm.RatingH2.ForeColor = Color.White
            GenreForm.RatingC1.ForeColor = Color.White
            GenreForm.RatingC2.ForeColor = Color.White
            GenreForm.RatingA1.ForeColor = Color.White
            GenreForm.RatingA2.ForeColor = Color.White
            GenreForm.RatingR1.ForeColor = Color.White
            GenreForm.RatingR2.ForeColor = Color.White

            Beverages.BackColor = Color.FromArgb(0, 0, 0)
            Beverages.nachostxt1.ForeColor = Color.White
            Beverages.nachostxt2.ForeColor = Color.White
            Beverages.nachostxt3.ForeColor = Color.White
            Beverages.coketxt1.ForeColor = Color.White
            Beverages.coketxt2.ForeColor = Color.White
            Beverages.coketxt3.ForeColor = Color.White
            Beverages.popcorntxt1.ForeColor = Color.White
            Beverages.popcorntxt2.ForeColor = Color.White
            Beverages.popcorntxt3.ForeColor = Color.White
            Beverages.popcorncarameltxt1.ForeColor = Color.White
            Beverages.popcorncarameltxt2.ForeColor = Color.White
            Beverages.popcorncarameltxt3.ForeColor = Color.White
            Beverages.popcorncheesetxt1.ForeColor = Color.White
            Beverages.popcorncheesetxt2.ForeColor = Color.White
            Beverages.popcorncheesetxt1.ForeColor = Color.White
            Beverages.combotxt1.ForeColor = Color.White
            Beverages.combotxt2.ForeColor = Color.White
            Beverages.combotxt3.ForeColor = Color.White

            Beverages2.BackColor = Color.FromArgb(0, 0, 0)
            Beverages2.nachostxt1.ForeColor = Color.White
            Beverages2.nachostxt2.ForeColor = Color.White
            Beverages2.nachostxt3.ForeColor = Color.White
            Beverages2.coketxt1.ForeColor = Color.White
            Beverages2.coketxt2.ForeColor = Color.White
            Beverages2.coketxt3.ForeColor = Color.White
            Beverages2.popcorntxt1.ForeColor = Color.White
            Beverages2.popcorntxt2.ForeColor = Color.White
            Beverages2.popcorntxt3.ForeColor = Color.White
            Beverages2.popcorncarameltxt1.ForeColor = Color.White
            Beverages2.popcorncarameltxt2.ForeColor = Color.White
            Beverages2.popcorncarameltxt3.ForeColor = Color.White
            Beverages2.popcorncheesetxt1.ForeColor = Color.White
            Beverages2.popcorncheesetxt2.ForeColor = Color.White
            Beverages2.popcorncheesetxt1.ForeColor = Color.White
            Beverages2.combotxt1.ForeColor = Color.White
            Beverages2.combotxt2.ForeColor = Color.White
            Beverages2.combotxt3.ForeColor = Color.White

            AboutUs.BackColor = Color.FromArgb(0, 0, 0)
            AboutUs.abt_pnl.BackColor = Color.FromArgb(0, 0, 0)
            AboutUs.abt_us_lbl.ForeColor = Color.White
            AboutUs.abt_us_detail_lbl.ForeColor = Color.White

            The_Nun.BackColor = Color.FromArgb(0, 0, 0)
            The_Nun.nun_panel.BackColor = Color.FromArgb(0, 0, 0)
            The_Nun.nun_format_pnl.BackColor = Color.FromArgb(0, 0, 0)
            The_Nun.Rating_lbl.ForeColor = Color.White
            The_Nun.dur_lbl.ForeColor = Color.White
            The_Nun.dur_time_lbl.ForeColor = Color.White
            The_Nun.rating_val_lbl.ForeColor = Color.White
            The_Nun.nun_desc.ForeColor = Color.White
            The_Nun.cast_lbl.ForeColor = Color.White
            The_Nun.cname1.ForeColor = Color.White
            The_Nun.cname2.ForeColor = Color.White
            The_Nun.cname3.ForeColor = Color.White
            The_Nun.cname4.ForeColor = Color.White
            The_Nun.top_review_lbl.ForeColor = Color.White
            The_Nun.reviews_lbl.ForeColor = Color.White
            The_Nun.user1_lbl.ForeColor = Color.White
            The_Nun.user1_review_lbl.ForeColor = Color.White
            The_Nun.user2_name_lbl.ForeColor = Color.White
            The_Nun.user2_review_lbl.ForeColor = Color.White
            The_Nun.username_lbl.ForeColor = Color.White
            The_Nun.user_review_output.ForeColor = Color.White
            The_Nun.add_review_lbl.ForeColor = Color.White
            'The_Nun.user_review_txt.ForeColor = Color.White
            The_Nun.moviename_lbl.ForeColor = Color.White
            The_Nun.format_nxt_btn.ForeColor = Color.White
            The_Nun.next_btn.ForeColor = Color.White
            The_Nun.select_format_lbl.ForeColor = Color.White
            The_Nun.btn_2d.ForeColor = Color.White
            The_Nun.btn_3d.ForeColor = Color.White
            'The_Nun.Add_btn.ForeColor = Color.White

            saw.sw_format_pnl.BackColor = Color.FromArgb(0, 0, 0)
            saw.BackColor = Color.FromArgb(0, 0, 0)
            saw.saw_panel.BackColor = Color.FromArgb(0, 0, 0)
            saw.sw_Rating_lbl.ForeColor = Color.White
            saw.sw_dur_lbl.ForeColor = Color.White
            saw.sw_dur_time_lbl.ForeColor = Color.White
            saw.sw_rating_val_lbl.ForeColor = Color.White
            saw.sw_desc.ForeColor = Color.White
            saw.sw_cast_lbl.ForeColor = Color.White
            saw.sw_cname1.ForeColor = Color.White
            saw.sw_cname2.ForeColor = Color.White
            saw.sw_cname3.ForeColor = Color.White
            saw.sw_cname4.ForeColor = Color.White
            saw.sw_top_review_lbl.ForeColor = Color.White
            saw.reviews_lbl.ForeColor = Color.White
            saw.sw_user1_lbl.ForeColor = Color.White
            saw.sw_user1_review_lbl.ForeColor = Color.White
            saw.sw_user2_name_lbl.ForeColor = Color.White
            saw.sw_user2_review_lbl.ForeColor = Color.White
            saw.sw_username_lbl.ForeColor = Color.White
            saw.sw_user_review_output.ForeColor = Color.White
            saw.sw_add_review_lbl.ForeColor = Color.White
            'saw.sw_user_review_txt.ForeColor = Color.White
            saw.sw_moviename_lbl.ForeColor = Color.White
            saw.sw_format_nxt_btn.ForeColor = Color.White
            saw.sw_next_btn.ForeColor = Color.White
            saw.sw_select_format_lbl.ForeColor = Color.White
            saw.sw_btn_2d.ForeColor = Color.White
            saw.sw_btn_3d.ForeColor = Color.White
            'saw.sw_Add_btn.ForeColor = Color.White

            'SUZUME DARK MODE CODE
            suzume.suz_format_pnl.BackColor = Color.FromArgb(0, 0, 0)
            suzume.BackColor = Color.FromArgb(0, 0, 0)
            suzume.suz_panel.BackColor = Color.FromArgb(0, 0, 0)
            suzume.s_Rating_lbl.ForeColor = Color.White
            suzume.s_dur_lbl.ForeColor = Color.White
            suzume.s_dur_time_lbl.ForeColor = Color.White
            suzume.s_rating_val_lbl.ForeColor = Color.White
            suzume.s_desc.ForeColor = Color.White
            suzume.s_cast_lbl.ForeColor = Color.White
            suzume.s_cname1.ForeColor = Color.White
            suzume.s_cname2.ForeColor = Color.White
            suzume.s_cname3.ForeColor = Color.White
            suzume.s_cname4.ForeColor = Color.White
            suzume.s_top_review_lbl.ForeColor = Color.White
            suzume.s_reviews_lbl.ForeColor = Color.White
            suzume.s_user1_lbl.ForeColor = Color.White
            suzume.s_user1_review_lbl.ForeColor = Color.White
            suzume.s_user2_name_lbl.ForeColor = Color.White
            suzume.s_user2_review_lbl.ForeColor = Color.White
            suzume.s_username_lbl.ForeColor = Color.White
            suzume.s_user_review_output.ForeColor = Color.White
            suzume.s_add_review_lbl.ForeColor = Color.White
            'suzume.s_user_review_txt.ForeColor = Color.White
            suzume.s_moviename_lbl.ForeColor = Color.White
            suzume.s_format_nxt_btn.ForeColor = Color.White
            suzume.s_next_btn.ForeColor = Color.White
            suzume.s_select_format_lbl.ForeColor = Color.White
            suzume.s_btn_2d.ForeColor = Color.White
            suzume.s_btn_3d.ForeColor = Color.White
            'suzume.s_Add_btn.ForeColor = Color.White
            'PATHAN DARK MODE CODE
            pathan.BackColor = Color.FromArgb(0, 0, 0)
            pathan.pathan_panel.BackColor = Color.FromArgb(0, 0, 0)
            pathan.pathan_format_pnl.BackColor = Color.FromArgb(0, 0, 0)
            pathan.pt_Rating_lbl.ForeColor = Color.White
            pathan.pt_dur_lbl.ForeColor = Color.White
            pathan.pt_dur_time_lbl.ForeColor = Color.White
            pathan.pt_rating_val_lbl.ForeColor = Color.White
            pathan.pt_desc.ForeColor = Color.White
            pathan.pt_cast_lbl.ForeColor = Color.White
            pathan.pt_cname1.ForeColor = Color.White
            pathan.pt_cname2.ForeColor = Color.White
            pathan.pt_cname3.ForeColor = Color.White
            pathan.pt_cname4.ForeColor = Color.White
            pathan.pt_top_review_lbl.ForeColor = Color.White
            pathan.pt_reviews_lbl.ForeColor = Color.White
            pathan.pt_user1_lbl.ForeColor = Color.White
            pathan.pt_user1_review_lbl.ForeColor = Color.White
            pathan.pt_user2_name_lbl.ForeColor = Color.White
            pathan.pt_user2_review_lbl.ForeColor = Color.White
            pathan.pt_username_lbl.ForeColor = Color.White
            pathan.pt_user_review_output.ForeColor = Color.White
            pathan.pt_add_review_lbl.ForeColor = Color.White
            'pathan.pt_user_review_txt.ForeColor = Color.White
            pathan.pt_moviename_lbl.ForeColor = Color.White
            pathan.pt_format_nxt_btn.ForeColor = Color.White
            pathan.pt_next_btn.ForeColor = Color.White
            pathan.pt_select_format_lbl.ForeColor = Color.White
            pathan.pt_btn_2d.ForeColor = Color.White
            pathan.pt_btn_3d.ForeColor = Color.White
            'pathan.pt_Add_btn.ForeColor = Color.White
            'RADHE DARK MODE CODE
            Radhe.BackColor = Color.FromArgb(0, 0, 0)
            Radhe.radhe_panel.BackColor = Color.FromArgb(0, 0, 0)
            Radhe.radhe_format_pnl.BackColor = Color.FromArgb(0, 0, 0)
            Radhe.rd_Rating_lbl.ForeColor = Color.White
            Radhe.rd_dur_lbl.ForeColor = Color.White
            Radhe.rd_dur_time_lbl.ForeColor = Color.White
            Radhe.rd_rating_val_lbl.ForeColor = Color.White
            Radhe.rd_desc.ForeColor = Color.White
            Radhe.rd_cast_lbl.ForeColor = Color.White
            Radhe.rd_cname1.ForeColor = Color.White
            Radhe.rd_cname2.ForeColor = Color.White
            Radhe.rd_cname3.ForeColor = Color.White
            Radhe.rd_cname4.ForeColor = Color.White
            Radhe.rd_top_review_lbl.ForeColor = Color.White
            Radhe.rd_reviews_lbl.ForeColor = Color.White
            Radhe.rd_user1_lbl.ForeColor = Color.White
            Radhe.rd_user1_review_lbl.ForeColor = Color.White
            Radhe.rd_user2_name_lbl.ForeColor = Color.White
            Radhe.rd_user2_review_lbl.ForeColor = Color.White
            Radhe.rd_username_lbl.ForeColor = Color.White
            Radhe.rd_user_review_output.ForeColor = Color.White
            Radhe.rd_add_review_lbl.ForeColor = Color.White
            'Radhe.rd_user_review_txt.ForeColor = Color.White
            Radhe.rd_moviename_lbl.ForeColor = Color.White
            Radhe.rd_format_nxt_btn.ForeColor = Color.White
            Radhe.rd_next_btn.ForeColor = Color.White
            Radhe.rd_select_format_lbl.ForeColor = Color.White
            Radhe.rd_btn_2d.ForeColor = Color.White
            Radhe.rd_btn_3d.ForeColor = Color.White
            'Radhe.rd_Add_btn.ForeColor = Color.White
            'TITANIC DARK MODE CODE
            Titanic.BackColor = Color.FromArgb(0, 0, 0)
            Titanic.Titanic_panel.BackColor = Color.FromArgb(0, 0, 0)
            Titanic.titanic_format_pnl.BackColor = Color.FromArgb(0, 0, 0)
            Titanic.TT_Rating_lbl.ForeColor = Color.White
            Titanic.TT_dur_lbl.ForeColor = Color.White
            Titanic.TT_dur_time_lbl.ForeColor = Color.White
            Titanic.TT_rating_val_lbl.ForeColor = Color.White
            Titanic.titanic_desc.ForeColor = Color.White
            Titanic.tt_cast_lbl.ForeColor = Color.White
            Titanic.TT_cname1.ForeColor = Color.White
            Titanic.TT_cname2.ForeColor = Color.White
            Titanic.TT_cname3.ForeColor = Color.White
            Titanic.TT_cname4.ForeColor = Color.White
            Titanic.TT_top_review_lbl.ForeColor = Color.White
            Titanic.TT_reviews_lbl.ForeColor = Color.White
            Titanic.TT_user1_lbl.ForeColor = Color.White
            Titanic.TT_user1_review_lbl.ForeColor = Color.White
            Titanic.TT_user2_name_lbl.ForeColor = Color.White
            Titanic.TT_user2_review_lbl.ForeColor = Color.White
            Titanic.TT_username_lbl.ForeColor = Color.White
            Titanic.TT_user_review_output.ForeColor = Color.White
            Titanic.TT_add_review_lbl.ForeColor = Color.White
            'Titanic.TT_user_review_txt.ForeColor = Color.White
            Titanic.TT_moviename_lbl.ForeColor = Color.White
            Titanic.TT_format_nxt_btn.ForeColor = Color.White
            Titanic.TT_next_btn.ForeColor = Color.White
            Titanic.TT_select_format_lbl.ForeColor = Color.White
            Titanic.TT_btn_2d.ForeColor = Color.White
            Titanic.TT_btn_3d.ForeColor = Color.White
            'Titanic.TT_Add_btn.ForeColor = Color.White
            'POSTER BOYS DARK MODE CODE
            poster_boys.BackColor = Color.FromArgb(0, 0, 0)
            poster_boys.poster_panel.BackColor = Color.FromArgb(0, 0, 0)
            poster_boys.poster_format_pnl.BackColor = Color.FromArgb(0, 0, 0)
            poster_boys.pb_Rating_lbl.ForeColor = Color.White
            poster_boys.pb_dur_lbl.ForeColor = Color.White
            poster_boys.pb_dur_time_lbl.ForeColor = Color.White
            poster_boys.pb_rating_val_lbl.ForeColor = Color.White
            poster_boys.pb_desc.ForeColor = Color.White
            poster_boys.pb_cast_lbl.ForeColor = Color.White
            poster_boys.pb_cname1.ForeColor = Color.White
            poster_boys.pb_cname2.ForeColor = Color.White
            poster_boys.pb_cname3.ForeColor = Color.White
            poster_boys.pb_cname4.ForeColor = Color.White
            poster_boys.pb_top_review_lbl.ForeColor = Color.White
            poster_boys.pb_reviews_lbl.ForeColor = Color.White
            poster_boys.pb_user1_lbl.ForeColor = Color.White
            poster_boys.pb_user1_review_lbl.ForeColor = Color.White
            poster_boys.pb_user2_name_lbl.ForeColor = Color.White
            poster_boys.pb_user2_review_lbl.ForeColor = Color.White
            poster_boys.pb_username_lbl.ForeColor = Color.White
            poster_boys.pb_user_review_output.ForeColor = Color.White
            poster_boys.pb_add_review_lbl.ForeColor = Color.White
            'poster_boys.pb_user_review_txt.ForeColor = Color.White
            poster_boys.pb_moviename_lbl.ForeColor = Color.White
            poster_boys.pb_format_nxt_btn.ForeColor = Color.White
            poster_boys.pb_next_btn.ForeColor = Color.White
            poster_boys.pb_select_format_lbl.ForeColor = Color.White
            poster_boys.pb_btn_2d.ForeColor = Color.White
            poster_boys.pb_btn_3d.ForeColor = Color.White
            'poster_boys.pb_Add_btn.ForeColor = Color.White
            'SHINCHAN DARK MODE CODE
            Shinchan.BackColor = Color.FromArgb(0, 0, 0)
            Shinchan.shinchan_panel.BackColor = Color.FromArgb(0, 0, 0)
            Shinchan.shinchan_format_pnl.BackColor = Color.FromArgb(0, 0, 0)
            Shinchan.sc_Rating_lbl.ForeColor = Color.White
            Shinchan.sc_dur_lbl.ForeColor = Color.White
            Shinchan.sc_dur_time_lbl.ForeColor = Color.White
            Shinchan.sc_rating_val_lbl.ForeColor = Color.White
            Shinchan.sc_desc.ForeColor = Color.White
            Shinchan.sc_cast_lbl.ForeColor = Color.White
            Shinchan.sc_cname1.ForeColor = Color.White
            Shinchan.sc_cname2.ForeColor = Color.White
            Shinchan.sc_cname3.ForeColor = Color.White
            Shinchan.sc_cname4.ForeColor = Color.White
            Shinchan.sc_top_review_lbl.ForeColor = Color.White
            Shinchan.sc_reviews_lbl.ForeColor = Color.White
            Shinchan.sc_user1_lbl.ForeColor = Color.White
            Shinchan.sc_user1_review_lbl.ForeColor = Color.White
            Shinchan.sc_user2_name_lbl.ForeColor = Color.White
            Shinchan.sc_user2_review_lbl.ForeColor = Color.White
            Shinchan.sc_username_lbl.ForeColor = Color.White
            Shinchan.sc_user_review_output.ForeColor = Color.White
            Shinchan.sc_add_review_lbl.ForeColor = Color.White
            'Shinchan.sc_user_review_txt.ForeColor = Color.White
            Shinchan.sc_moviename_lbl.ForeColor = Color.White
            Shinchan.sc_format_nxt_btn.ForeColor = Color.White
            Shinchan.sc_next_btn.ForeColor = Color.White
            Shinchan.sc_select_format_lbl.ForeColor = Color.White
            Shinchan.sc_btn_2d.ForeColor = Color.White
            Shinchan.sc_btn_3d.ForeColor = Color.White
            'Shinchan.sc_Add_btn.ForeColor = Color.White
            'Lallu DARKMODE CODE
            Lallu.BackColor = Color.FromArgb(0, 0, 0)
            Lallu.lallu_panel.BackColor = Color.FromArgb(0, 0, 0)
            Lallu.lallu_format_pnl.BackColor = Color.FromArgb(0, 0, 0)
            Lallu.ll_Rating_lbl.ForeColor = Color.White
            Lallu.ll_dur_lbl.ForeColor = Color.White
            Lallu.ll_dur_time_lbl.ForeColor = Color.White
            Lallu.ll_rating_val_lbl.ForeColor = Color.White
            Lallu.ll_desc.ForeColor = Color.White
            Lallu.ll_cast_lbl.ForeColor = Color.White
            Lallu.ll_cname1.ForeColor = Color.White
            Lallu.ll_cname2.ForeColor = Color.White
            Lallu.ll_cname3.ForeColor = Color.White
            Lallu.ll_cname4.ForeColor = Color.White
            Lallu.ll_top_review_lbl.ForeColor = Color.White
            Lallu.ll_reviews_lbl.ForeColor = Color.White
            Lallu.ll_user1_lbl.ForeColor = Color.White
            Lallu.ll_user1_review_lbl.ForeColor = Color.White
            Lallu.ll_user2_name_lbl.ForeColor = Color.White
            Lallu.ll_user2_review_lbl.ForeColor = Color.White
            Lallu.ll_username_lbl.ForeColor = Color.White
            Lallu.ll_user_review_output.ForeColor = Color.White
            Lallu.ll_add_review_lbl.ForeColor = Color.White
            ' Lallu.ll_user_review_txt.ForeColor = Color.White
            Lallu.ll_moviename_lbl.ForeColor = Color.White
            Lallu.ll_format_nxt_btn.ForeColor = Color.White
            Lallu.ll_next_btn.ForeColor = Color.White
            Lallu.II_select_format_lbl.ForeColor = Color.White
            Lallu.ll_btn_2d.ForeColor = Color.White
            Lallu.ll_btn_3d.ForeColor = Color.White
            'Lallu.ll_Add_btn.ForeColor = Color.White

            TandC.BackColor = Color.Black
            TandC.Label2.ForeColor = Color.White

            movie1___Date1__.todaypathandate1.BackColor = Color.Black
            movie1___Date1__.tomorrowpathandate1.BackColor = Color.Black
            movie1___Date1__.Dayaftertomorrowpathandate1.BackColor = Color.Black
            movie1___Date1__.todaypathandate1.ForeColor = Color.White
            movie1___Date1__.tomorrowpathandate1.ForeColor = Color.White
            movie1___Date1__.Dayaftertomorrowpathandate1.ForeColor = Color.White

            movie1_date1_.panelPanel2today.BackColor = Color.Black
            movie1_date1_.screen1movie1date1.ForeColor = Color.White
            movie1_date1_.screen1movie1date1.BackColor = Color.Black
            movie1_date1_.screen2movie1date1.ForeColor = Color.White
            movie1_date1_.screen2movie1date1.BackColor = Color.Black
            movie1_date1_.screen3moviedate1.ForeColor = Color.White
            movie1_date1_.screen3moviedate1.BackColor = Color.Black
            movie1_date1_.noncancellable1.ForeColor = Color.White
            movie1_date1_.noncancellable2.ForeColor = Color.White
            movie1_date1_.cancellable1.ForeColor = Color.White

            movie1___Date_2__.Panel2tomorrow.BackColor = Color.Black
            movie1___Date_2__.screen1movie1date2.ForeColor = Color.White
            movie1___Date_2__.screen2movie1date2.ForeColor = Color.White
            movie1___Date_2__.screen3moviedate2.ForeColor = Color.White
            movie1___Date_2__.noncancellable1date2.ForeColor = Color.White
            movie1___Date_2__.noncancellable2date2.ForeColor = Color.White
            movie1___Date_2__.cancellable1date2.ForeColor = Color.White


            movie1___date_3_.panelPanel2dayaftertomorrow.BackColor = Color.Black
            movie1___date_3_.screen1movie1date3.ForeColor = Color.White
            movie1___date_3_.screen2movie1date3.ForeColor = Color.White
            movie1___date_3_.screen3moviedate3.ForeColor = Color.White
            movie1___date_3_.noncancellable1date3.ForeColor = Color.White
            movie1___date_3_.noncancellable2date3.ForeColor = Color.White
            movie1___date_3_.cancellable1date3.ForeColor = Color.White

            Screen1.BackColor = Color.Black
            Screen1.Label1.ForeColor = Color.White
            Screen1.Label2.ForeColor = Color.White
            Screen1.Label3.ForeColor = Color.White
            Screen1.Label4.ForeColor = Color.White
            Screen1.Label13.ForeColor = Color.White
            Screen1.Label28.ForeColor = Color.White
            Screen1.Label29.ForeColor = Color.White

            Screen2.BackColor = Color.Black
            Screen2.Label1.ForeColor = Color.White
            Screen2.Label2.ForeColor = Color.White
            Screen2.Label3.ForeColor = Color.White
            Screen2.Label4.ForeColor = Color.White
            Screen2.Label13.ForeColor = Color.White
            Screen2.Label28.ForeColor = Color.White
            Screen2.Label29.ForeColor = Color.White

            PaymentForm.Panel1.BackColor = Color.Black
            PaymentForm.Panel1.ForeColor = Color.White

            TicketForm.BackColor = Color.Black
            TicketForm.ForeColor = Color.White
            TicketForm.ScanLabel.ForeColor = Color.White
            TicketForm.Label1.ForeColor = Color.White
            TicketForm.Label2.ForeColor = Color.White
            TicketForm.Label3.ForeColor = Color.White
            TicketForm.Label4.ForeColor = Color.White
            TicketForm.SeatLabel.ForeColor = Color.White
            TicketForm.TotalLabel.ForeColor = Color.White
            TicketForm.BevLabel.ForeColor = Color.White
            TicketForm.TotLabel.ForeColor = Color.White
        End If



    End Sub

    Private Sub cross_Click(sender As Object, e As EventArgs) Handles cross.Click
        Me.Close()
    End Sub

    Private Sub minus_Click(sender As Object, e As EventArgs) Handles minus.Click
        Me.WindowState = WindowState.Minimized
    End Sub

    Private Sub MainPanel_Paint(sender As Object, e As PaintEventArgs) Handles MainPanel.Paint

    End Sub
End Class
